### ISSUE TITLE
FR: Update Ubuntu / PostgreSQL Client

### ISSUE THREAD

**Issue by scholejo** [craftcms/image#16]
### Description

It's not possible to dump the database when running with a PostgreSQL 16 Server, which is the recommended version of PostgreSQL for Craft 5.
This is because the Images are based on Ubuntu 22.04 LTS which only comes with PostgreSQL 14. Currently, we are updating the PostgreSQL client in our own Dockerfile based on your PHP 8.3 image, but it would be nice to have the most recent LTS version of Ubuntu anyway, which comes with PostgreSQL 16. Is that possible? Maybe as an own tag? Alternatively, could you update just the PostgreSQL Client in the images?

I've seen the section on updating Ubuntu in the Readme, but I still think it would be nicer to have the images come with the most recent LTS version of Ubuntu.

### Steps to reproduce

1. Start a (PHP 8.3) Container
2. Connect it to a PostgreSQL (v16) Server
3. Dump the database (I only tested that via Command Line)
4. You should see a version mismatch error from PostgreSQL

### Additional info

- Craft version: 5.x
- PHP version: 8.3
- Database driver & version: PostgreSQL 16
- Plugins & versions:

**Comment by jasonmccallister** [comment]
@scholejo we just released the `8.4` version of these images where the Ubuntu version is now 24.04. I am hesitant to update the existing branches/versions (e.g. `8.3`) to the new ubuntu version as there will likely be some dependencies that are changed and don't want to break anyones current working environment. 

Regarding backups - we often rely on third-party tools in container based environments because of the intricacies of performing backups between DB drivers and specifically versions. This also keeps the container images lightweight. 

Let me know if you have any additional questions!

**Comment by scholejo** [comment]
Hi @jasonmccallister, thanks for letting me know! I think we're totally fine with using the `8.4` variants. That's, in fact, even better for us.
